# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed645cc8fd4994db30cb50730965dbe710baf8baebb60f28419b6d8c567b25efa4e1a02e83729297b588937e4e2d2bfe56c80eac12de63748279e7992f14d8fc

test:
  secret_key_base: 58951067b801b9188e58278cee4dc6ed7280276d01132811f3cefa8f74159d81dfad017d83ef535899d07a5f69c6041be79b889159d1f26973c71c77d6bc3746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
